# SLURM Database Configuration
database:
  host: "slurm-db-server.example.com"
  port: 3306
  database: "slurm_acct_db"
  username: "slurm_readonly_user"
  password: "your_password_here"
  cluster_name: "cluster1"
  
# Data extraction settings
extraction:
  # Output file format: 'csv', 'parquet', or 'json'
  output_format: "parquet"
  # Output directory for data files
  output_dir: "data"
  # Batch size for splitting up the SQL queries
  batch_size: 10000
  # Whether to clean up individual batch files after consolidation
  cleanup_batch_files: false
  # Date range for job extraction (optional, leave empty for all jobs)
  start_date: null  # Format: "YYYY-MM-DD" or null for no limit
  end_date: null    # Format: "YYYY-MM-DD" or null for no limit

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file: "logs/slurm_extractor.log" 